# .travis.yml

cache:
    directories:
      - ~/.npm
  
#   script:
    # - npm test
  
  stages:
    - test
    - name: release
      if: branch = master AND type = push AND fork = false
  
  jobs:
    include:
      - stage: release
        language: node_js
        node_js: '10.18'
        script: npm run semantic-release